### ISSUE TITLE
Older versions of Delphi

### ISSUE THREAD

**Issue by michaelrempel** [grijjy/DelphiZeroMQ#2]
When I look at the source code, the only major thing stopping use of this library with older versions of Delphi is the use of Managed Types.

I am using XE3 and cannot afford to upgrade at the moment. I imagine that managed types provide a cleaner smaller footprint, but is it possible to use this code effectively without them?

Also what do I need to do to make it work without Managed types?

**Comment by allendrennan** [comment]
While we don’t have or test with XE3 currently, we may be able to help or provide advice.  Could you provide the compile error lines/locations that you receive from Delphi XE3?
